### ISSUE TITLE
how to add other pose of 3dmodels

### ISSUE THREAD

**Issue by ElanallyLi** [iacopomasi/face_specific_augm#10]
hello, how do you create the 3d models and whats the difference of the 10 different models in one pose。Besides,what the 3d models inside contains and how can i create new pose model? 
(I am a new beginner and a student,thank you very much.)

**Comment by iacopomasi** [comment]
Hi @ElanallyLi ,
the 3D rendered views are created beforehand in MATLAB with a script. Currently, this process has not been released yet but we might decide to release it soon. This will allow for example to have precomputed view to render pitch variations as well or more angles.

The MATLAB script to generate the 3D rendered views uses MATLAB + [a CG renderer](https://www.openu.ac.il/home/hassner/projects/poses/).

If you have a 3D generic model you can try on your own but you need to format the data in the `.mat` file  in the same way I did in order to use it with the renderer.
