### ISSUE TITLE
Questions about 3D Rendering of Face Image used in Face Specific Augmentation

### ISSUE THREAD

**Issue by chamantonio** [iacopomasi/face_specific_augm#15]
Hi, developers!

We are trying to create a headless renderer for facial images and we’ve seen your successful work in rendering. However, we are using different inputs for the renderer that we are trying to create. Still, we’re trying to use your project as reference. We would appreciate it if you can give us a brief explanation of how the renderer works. To be specific, what are these parameters? 

- proj_matrix
- ref_U
- eyemask
- facemask
- opts

We hope to hear from you soon. Your answers can help support the computer vision research field. Thank you so much!

**Comment by iacopomasi** [comment]
Hi @chamantonio,

for a general overview, you can read this paper: 

```Masi, I., Hassner, T., Tran, A. T., & Medioni, G. (2017, May). Rapid synthesis of massive face sets for improved face recognition. In Automatic Face & Gesture Recognition (FG 2017), 2017 12th IEEE International Conference on (pp. 604-611). IEEE.```

The link is [here](http://www.openu.ac.il/home/hassner/projects/augmented_faces/Masietal2017rapid.pdf) 


Quick reply:

- proj_matrix: is the 3x4 projection matrix from 3D to 2D; from the 3D face to the 2D image. It is **M** in Eq. (2) of the paper.
- ref_U: is the 224x224 unprojected matrix that contains the 3D coordinates in each channel and serves as a look-up table.  For a 3D point in ref_U, say  `ref_U[i,j]`you project it to the image, you sample the texture and then you know how to generate the rendered image since the indices of the matrix will tell you where to write the sampled texture (in [i,j]; This is quickly performed using the 2D interpolation function `cv2.remap()`. The rendered view is basically ` ref_U` but replaced with the texture content. See Eq. (1) in the paper.
- eyemask and facemask: indices of ref_U that contains the inner part of the faces (without the head) and those of the eyes only. See the config file parameter [`background`](https://github.com/iacopomasi/face_specific_augm/blob/master/config.ini#L25) to render without the head.

Other very related project you might be interested in:

- [FacePoseNet](https://github.com/fengju514/Face-Pose-Net)
- [MATLAB 3D Model Renderer](https://www.openu.ac.il/home/hassner/projects/poses/)

I hope this helps.

**Comment by chamantonio** [comment]
Thank you! Will try to work with this info.
